import Link from "next/link";

const steps=[
  ["01","Clarify the goal","We start with your timing, priorities, preferred areas, and what you need from your next home."],
  ["02","Build the financial picture","A trusted lender helps establish a comfortable budget and explains financing, cash needs, and closing costs."],
  ["03","Understand the market","We look at communities, property types, commutes, ownership costs, and current competition."],
  ["04","Look beyond the first impression","We consider the layout, major systems, likely maintenance, and how the home may fit your life over time."],
  ["05","Build your offer","Together, we weigh price, timing, financing, contingencies, and the seller’s priorities."],
  ["06","Investigate the property","Inspections, title, appraisal, insurance, and documents help you make an informed commitment."],
  ["07","Prepare for closing","We confirm the final details, complete the walkthrough, and prepare you for what comes next."],
  ["08","Support after closing","My goal is to remain a useful resource for property questions, trusted contacts, and future decisions."],
];

export default function BuyerRoadmap(){return <main><header className="site-header"><Link className="brand" href="/"><span>Salt &amp; Light</span><small>Real Estate</small></Link><nav><Link href="/">Home</Link><Link href="/articles">Articles</Link><Link href="/card">Digital card</Link></nav><Link className="header-cta" href="/contact">Let&apos;s talk</Link></header><article className="guide"><header className="guide-hero"><p className="eyebrow">Buying in Hampton Roads</p><h1>Your Buyer Roadmap</h1><p>A practical guide to buying a home in Hampton Roads, from getting prepared to closing day and beyond.</p><div className="guide-meta"><span>Emmanuel Maldonado</span><span>Salt &amp; Light Real Estate</span><span>Brokered by Rooted Residential</span></div></header><section className="guide-intro"><h2>The right home begins with the right questions.</h2><div><p>Buying a home affects your finances and your daily life. My job is to help you understand your options, talk through the tradeoffs, and move forward when the choice is right for you.</p><p>This roadmap outlines the process, but every purchase is different. We will adjust each step to fit your situation.</p></div></section><section className="roadmap">{steps.map(([number,title,copy])=><div className="roadmap-step" key={number}><span>{number}</span><h2>{title}</h2><p>{copy}</p></div>)}</section><aside className="guide-note"><p className="eyebrow">A property management perspective</p><h2>A showing is only part of the picture.</h2><p>Maintenance, major systems, recurring costs, and future flexibility can matter just as much as paint colors and first impressions.</p></aside><section className="guide-cta"><div><p className="eyebrow">Your first step</p><h2>Start with a conversation.</h2><p>We’ll talk about your goals, answer your questions, and figure out what makes sense for you.</p></div><Link className="button button-light" href="/contact">Contact Emmanuel</Link></section></article><footer><span>© 2026 Salt &amp; Light Real Estate</span><span>Brokered by Rooted Residential</span><Link href="/articles">More guides &amp; insights</Link></footer></main>}
